<?php
/**
 * RephrasedSentence
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * nlpapiv2
 *
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * RephrasedSentence Class Doc Comment
 *
 * @category Class
 * @description One input sentence and associated rephrasing results
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RephrasedSentence implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RephrasedSentence';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'sentence_index' => 'int',
        'original_sentence_text' => 'string',
        'rephrasings' => '\Swagger\Client\Model\RephrasedSentenceOption[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'sentence_index' => 'int32',
        'original_sentence_text' => null,
        'rephrasings' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sentence_index' => 'SentenceIndex',
        'original_sentence_text' => 'OriginalSentenceText',
        'rephrasings' => 'Rephrasings'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sentence_index' => 'setSentenceIndex',
        'original_sentence_text' => 'setOriginalSentenceText',
        'rephrasings' => 'setRephrasings'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sentence_index' => 'getSentenceIndex',
        'original_sentence_text' => 'getOriginalSentenceText',
        'rephrasings' => 'getRephrasings'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['sentence_index'] = isset($data['sentence_index']) ? $data['sentence_index'] : null;
        $this->container['original_sentence_text'] = isset($data['original_sentence_text']) ? $data['original_sentence_text'] : null;
        $this->container['rephrasings'] = isset($data['rephrasings']) ? $data['rephrasings'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets sentence_index
     *
     * @return int
     */
    public function getSentenceIndex()
    {
        return $this->container['sentence_index'];
    }

    /**
     * Sets sentence_index
     *
     * @param int $sentence_index Index of the sentence, 1-based, ordered
     *
     * @return $this
     */
    public function setSentenceIndex($sentence_index)
    {
        $this->container['sentence_index'] = $sentence_index;

        return $this;
    }

    /**
     * Gets original_sentence_text
     *
     * @return string
     */
    public function getOriginalSentenceText()
    {
        return $this->container['original_sentence_text'];
    }

    /**
     * Sets original_sentence_text
     *
     * @param string $original_sentence_text Original input sentence text
     *
     * @return $this
     */
    public function setOriginalSentenceText($original_sentence_text)
    {
        $this->container['original_sentence_text'] = $original_sentence_text;

        return $this;
    }

    /**
     * Gets rephrasings
     *
     * @return \Swagger\Client\Model\RephrasedSentenceOption[]
     */
    public function getRephrasings()
    {
        return $this->container['rephrasings'];
    }

    /**
     * Sets rephrasings
     *
     * @param \Swagger\Client\Model\RephrasedSentenceOption[] $rephrasings Rephrasing text options, candidates of the original input sentence, in order - with best candidate first
     *
     * @return $this
     */
    public function setRephrasings($rephrasings)
    {
        $this->container['rephrasings'] = $rephrasings;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


