<?php
/**
 * ProfanityAnalysisResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * nlpapiv2
 *
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProfanityAnalysisResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description Output of a profanity analysis operation
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProfanityAnalysisResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProfanityAnalysisResponse"
     */
    public function testProfanityAnalysisResponse()
    {
    }

    /**
     * Test attribute "successful"
     */
    public function testPropertySuccessful()
    {
    }

    /**
     * Test attribute "profanity_score_result"
     */
    public function testPropertyProfanityScoreResult()
    {
    }

    /**
     * Test attribute "sentence_count"
     */
    public function testPropertySentenceCount()
    {
    }
}
