<?php
/**
 * AnalyticsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * nlpapiv2
 *
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * AnalyticsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AnalyticsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for analyticsHateSpeech
     *
     * Perform Hate Speech Analysis and Detection on Text.
     *
     */
    public function testAnalyticsHateSpeech()
    {
    }

    /**
     * Test case for analyticsProfanity
     *
     * Perform Profanity and Obscene Language Analysis and Detection on Text.
     *
     */
    public function testAnalyticsProfanity()
    {
    }

    /**
     * Test case for analyticsSentiment
     *
     * Perform Sentiment Analysis and Classification on Text.
     *
     */
    public function testAnalyticsSentiment()
    {
    }

    /**
     * Test case for analyticsSimilarity
     *
     * Perform Semantic Similarity Comparison of Two Strings.
     *
     */
    public function testAnalyticsSimilarity()
    {
    }

    /**
     * Test case for analyticsSubjectivity
     *
     * Perform Subjectivity and Objectivity Analysis on Text.
     *
     */
    public function testAnalyticsSubjectivity()
    {
    }
}
