<?php
/**
 * LanguageTranslationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * nlpapiv2
 *
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * LanguageTranslationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LanguageTranslationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for languageTranslationTranslateDeuToEng
     *
     * Translate German to English text with Deep Learning AI.
     *
     */
    public function testLanguageTranslationTranslateDeuToEng()
    {
    }

    /**
     * Test case for languageTranslationTranslateEngToDeu
     *
     * Translate English to German text with Deep Learning AI.
     *
     */
    public function testLanguageTranslationTranslateEngToDeu()
    {
    }

    /**
     * Test case for languageTranslationTranslateEngToFra
     *
     * Translate English to French text with Deep Learning AI.
     *
     */
    public function testLanguageTranslationTranslateEngToFra()
    {
    }

    /**
     * Test case for languageTranslationTranslateEngToRus
     *
     * Translate English to Russian text with Deep Learning AI.
     *
     */
    public function testLanguageTranslationTranslateEngToRus()
    {
    }

    /**
     * Test case for languageTranslationTranslateFraToEng
     *
     * Translate French to English text with Deep Learning AI.
     *
     */
    public function testLanguageTranslationTranslateFraToEng()
    {
    }

    /**
     * Test case for languageTranslationTranslateRusToEng
     *
     * Translate Russian to English text with Deep Learning AI.
     *
     */
    public function testLanguageTranslationTranslateRusToEng()
    {
    }
}
