<?php
/**
 * PosTaggerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * nlpapiv2
 *
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * PosTaggerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PosTaggerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for posTaggerTagAdjectives
     *
     * Part-of-speech tag a string, filter to adjectives.
     *
     */
    public function testPosTaggerTagAdjectives()
    {
    }

    /**
     * Test case for posTaggerTagAdverbs
     *
     * Part-of-speech tag a string, filter to adverbs.
     *
     */
    public function testPosTaggerTagAdverbs()
    {
    }

    /**
     * Test case for posTaggerTagNouns
     *
     * Part-of-speech tag a string, filter to nouns.
     *
     */
    public function testPosTaggerTagNouns()
    {
    }

    /**
     * Test case for posTaggerTagPronouns
     *
     * Part-of-speech tag a string, filter to pronouns.
     *
     */
    public function testPosTaggerTagPronouns()
    {
    }

    /**
     * Test case for posTaggerTagSentence
     *
     * Part-of-speech tag a string.
     *
     */
    public function testPosTaggerTagSentence()
    {
    }

    /**
     * Test case for posTaggerTagVerbs
     *
     * Part-of-speech tag a string, filter to verbs.
     *
     */
    public function testPosTaggerTagVerbs()
    {
    }
}
