<?php
/**
 * SpellCheckApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * nlpapi
 *
 * The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * SpellCheckApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SpellCheckApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for spellCheckCheckJson
     *
     * Spell check word.
     *
     */
    public function testSpellCheckCheckJson()
    {
    }

    /**
     * Test case for spellCheckCheckSentenceJson
     *
     * Check if sentence is spelled correctly.
     *
     */
    public function testSpellCheckCheckSentenceJson()
    {
    }

    /**
     * Test case for spellCheckCheckSentenceString
     *
     * Spell check a sentence.
     *
     */
    public function testSpellCheckCheckSentenceString()
    {
    }

    /**
     * Test case for spellCheckCorrect
     *
     * Find spelling corrections.
     *
     */
    public function testSpellCheckCorrect()
    {
    }

    /**
     * Test case for spellCheckCorrectJson
     *
     * Find spelling corrections.
     *
     */
    public function testSpellCheckCorrectJson()
    {
    }

    /**
     * Test case for spellCheckPost
     *
     * Spell check a word.
     *
     */
    public function testSpellCheckPost()
    {
    }
}
