<?php
/**
 * WordsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * nlpapi
 *
 * The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * WordsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WordsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for wordsAdjectives
     *
     * Get adjectives in string.
     *
     */
    public function testWordsAdjectives()
    {
    }

    /**
     * Test case for wordsAdverbs
     *
     * Get adverbs in input string.
     *
     */
    public function testWordsAdverbs()
    {
    }

    /**
     * Test case for wordsGetWordsJson
     *
     * Get words in input string (JSON).
     *
     */
    public function testWordsGetWordsJson()
    {
    }

    /**
     * Test case for wordsGetWordsString
     *
     * Get words from string.
     *
     */
    public function testWordsGetWordsString()
    {
    }

    /**
     * Test case for wordsNouns
     *
     * Get nouns in string.
     *
     */
    public function testWordsNouns()
    {
    }

    /**
     * Test case for wordsPost
     *
     * Get the verbs in a string.
     *
     */
    public function testWordsPost()
    {
    }

    /**
     * Test case for wordsPronouns
     *
     * Returns all pronounts in string.
     *
     */
    public function testWordsPronouns()
    {
    }

    /**
     * Test case for wordsProperNouns
     *
     * Get proper nouns in a string.
     *
     */
    public function testWordsProperNouns()
    {
    }
}
